version: '3'

x-base: &base
    env_file:
        - .env


networks:
  API:
    driver: bridge


services:

  redis:
    image: redis
    container_name: 'redis_cache'
    restart: unless-stopped
    networks:
      - API
    command:
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    ports:
      - ${REDIS_PORT}:6379

  pg:
    image: postgres:13
    env_file:
      - .env
    networks:
      - API
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./etl/dump:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432

  elasticsearch:
    image: 'ghcr.io/yp-middle-python-24/elasticsearch:8.7.0'
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
    networks:
      - API
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  fast_api:
    build:
      context: async_api
    env_file:
      - .env
    ports:
      - ${FAST_API_PORT}:${FAST_API_PORT}
    networks:
      - API

  etl:
    build:
      context: etl/postgres_to_es
    env_file:
      - .env